apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  creationTimestamp: null
  labels:
    app: sample-lambda
    created-by: kubeless
    function: sample-lambda
  name: sample-lambda
  namespace: demo-flux
spec:
  checksum: sha256:00cb98472b271e89f130baf6056c15810d38b2d91c4e03e6465700a887660565
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      selector: null
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - imagePullPolicy: Always
            name: ""
            resources: {}
    status: {}
  deps: |-
    {
        "name": "sample-lambda",
        "main": "sample-lambda.js",
        "license": "Unlicense",
        "dependencies": {
          "yaml": "^1.7.2"
        },
        "devDependencies": {
          "gulp": "^4.0.2"
        }
      }
  function: |-
    module.exports = {
        main: async function (event, context) {
            return "hello world"
        }
    }
  function-content-type: text
  handler: handler.main
  horizontalPodAutoscaler:
    metadata:
      creationTimestamp: null
    spec:
      maxReplicas: 0
      scaleTargetRef:
        kind: ""
        name: ""
    status:
      conditions: null
      currentMetrics: null
      currentReplicas: 0
      desiredReplicas: 0
  runtime: nodejs8
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: sample-lambda
      created-by: kubeless
      function: sample-lambda
    type: ClusterIP
  timeout: "180"

