# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/abbi-gaurav/kyma-gitops
    steps:
      - checkout
      - run: GO111MODULE=on GO_APP_ENV="test" go test ./smoke_test -v
      - store_artifacts:
          path: /tmp/reports
workflows:
  test:
    jobs:
      - test
          filters:
            branches:
              only:
                - dev