# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/abbi-gaurav/kyma-gitops
    steps:
      - checkout
      - run: GO111MODULE=on GO_APP_ENV="test" TEST_NAME="Lambda" API_URL=$LAMBDA_API_URL go test ./smoke_test -v
workflows:
  # Name the workflow "welcome"
  test:
    # Run the welcome/run job in its own container
    jobs:
      - test